pairprogramming/urls.py
from django.contrib import admin
from django.urls import path, include
from user.views import signin, signinForm, TopicAutoComplete,autocomplete

urlpatterns = [
    path('admin/', admin.site.urls),
    path('u/', include('user.urls')),
    path('signin/', signinForm, name='signinForm'),
    path('signmein/', signin, name='signmein'),
    path('autocomplete/', autocomplete, name='autocomplete'),

]

project/urls.py
from django.urls import  path


app_name = 'project'
urlpatterns = [

]

user/urls.py
from django.urls import path
from user import views


app_name = 'user'
urlpatterns = [
    path('<user_name>/', views.index, name='profile'),
    path('<user_name>/feed/', views.feed, name='feed'),
    path('<user_name>/projects/', views.projects, name='projects'),
    path('<user_name>/timeline/', views.timeline, name='timeline'),
    path('<user_name>/mystory/', views.mystory, name='mystory'),
    path('<user_name>/following/', views.following, name='following'),
    path('<user_name>/followers/', views.followers, name='followers'),
]

project/models.py
from django.db import models
from user.models import User

user/models.py
from django.db import models
from .choices import IDEA_STATUS
import random


RELATIONSHIP_FOLLOWING      = 1
RELATIONSHIP_BLOCKED        = 2
RELATIONSHIP_PENDING        = 3
RELATIONSHIP_STATUSES = (
    (RELATIONSHIP_FOLLOWING, "Following"),
    (RELATIONSHIP_BLOCKED, 'Blocked'),
    (RELATIONSHIP_PENDING, 'Pending'),
)


class User(models.Model):

    user_name            = models.CharField(max_length=100, default=''.join(random.choice('abcdefghijklmnopqrstuvwxyz') for _ in range(6)))
    user_email           = models.EmailField(default='rajivpensidpri@gmail.com')
    user_about           = models.TextField(max_length=500, default='ab')
    user_github_token    = models.CharField(max_length=500,default='abb')
    user_relationships   = models.ManyToManyField('self', related_name='related_to', symmetrical=False, through='Relationship')
    user_followers       = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.user_name

    def add_relationship(self, user, status):
        relationship, created = Relationship.objects.get_or_create(
            from_user = self,
            to_user   = user,
            status    = status
        )
        return relationship

    def remove_relationship(self, user, status):
        Relationship.objects.filter(
            from_user = self,
            to_user   = user,
            status    = status
        ).delete()
        return

    def get_relationships(self, status):
        return self.user_relationships.filter(        ## Lists all the users with whom the 'self' is in a Relationship with
            to_relationships__status=status,
            to_relationships__from_user=self          ## Filter the users whose to_relationships contain 'self' as from_user.
        )

    def get_related_to(self, status):
        return self.related_to.filter(
            from_relationships__status=status,
            from_relationships__to_user=self
        )

    def get_following(self):
        return self.get_relationships(RELATIONSHIP_FOLLOWING)

    def get_followers(self):
        return self.get_related_to(RELATIONSHIP_FOLLOWING)

    def get_projects(self):
        return self.user_projects.all()




class Relationship(models.Model):

    # user.from_relationships --> Gives all the relationships that emerge from user--> AnotherUser
    from_user = models.ForeignKey(User, related_name='from_relationships', on_delete=models.CASCADE)

    # user.to_relationships --> Gives all the relationships that end in user. AnotherUser --> user
    to_user   = models.ForeignKey(User, related_name='to_relationships', on_delete=models.CASCADE)

    status    = models.IntegerField(choices=RELATIONSHIP_STATUSES)


class Idea(models.Model):
    idea_title            = models.CharField(max_length=100, default='my awesome idea')
    idea_description      = models.TextField(max_length=500, default='my awesome idea')
    idea_owner            = models.ForeignKey(User, on_delete=models.CASCADE, related_name='owned_ideas', blank=True)
    idea_interested_users = models.ManyToManyField(User, blank=True)
    idea_upvotes          = models.PositiveIntegerField(default=0)
    idea_downvotes        = models.PositiveIntegerField(default=0)
    idea_status           = models.IntegerField(choices=IDEA_STATUS, default=1)


# class Repo(models.Model):
#     repo_name        = models.CharField(max_length=100)
#     repo_url         = models.URLField(max_length=500)
#     repo_owner       = models.ForeignKey(User, on_delete=models.CASCADE, related_name='owned_repos')
#     repo_members     = models.ManyToManyField(User)
#     repo_forks       = models.PositiveIntegerField(default=0)
#     repo_stars       = models.PositiveIntegerField(default=0)
#     repo_description = models.TextField(max_length=500)
#     repo_pub         = models.DateTimeField()


class Topic(models.Model):
    topic_title          = models.CharField(max_length=100)
    topic_ideas          = models.ManyToManyField(Idea, related_name='related_topics', blank=True)
    topic_followers      = models.ManyToManyField(User, related_name='interested_areas', blank=True)


class Tag(models.Model):
    tag_title            = models.CharField(max_length=30)


class Project(models.Model):
    project_title        = models.CharField(max_length=30)
    project_summary      = models.TextField(max_length=500, default='My Awesome project')
    project_members      = models.ManyToManyField(User, related_name='user_projects')

    def get_members(self):
        return self.project_members.all()

user/forms.py
from django import forms
from dal import autocomplete
from user.models import Topic


class TopicForm(forms.ModelForm):

    topic = forms.ModelChoiceField(
        query_set = Topic.objects.all(),
        widget    = autocomplete.ModelSelect2(url='autocomplete', attrs={'data-minimum-input-length': 2, 'data-placeholder': 'Autocomplete ...',},)

    )

    class Meta:
        model     = Topic
        fields    = '__all__'

project/views.py
from django.shortcuts import render

# Create your views here.

user/views.py
from django.shortcuts import render
from django.urls import reverse
from django.views import generic
from user.models import User, Idea
from user.models import Topic
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from github import Github
from user.utils import *
from dal import autocomplete


class TopicAutoComplete(autocomplete.Select2QuerySetView):
    #TODO : Don't forget to add proper permission checks to the querying user.
    def get_queryset(self):

        qs = Topic.objects.all()
        if self.q:
            qs = qs.filter(topic_title__isstartswith=self.q)
        return qs[:10]


def autocomplete(request):
    topics = Topic.objects.all()
    tags = [t.topic_title for t in topics]
    return JsonResponse(list(set(tags))[:5000], safe=False)


def index(request, user_name):
    add_all_topics()
    topics = Topic.objects.all()
    user   = User.objects.get(user_name=user_name)

    context = {
        'user_name': user_name,
        'topics'   : topics,
        'no_of_followers': 10,
        'my_name' : request.session['user_name'],
        'user_about' : user.user_about
    }
    return render(request, 'user/profile.html', context)


def signinForm(request):
    return render(request, 'signin.html', None)


def signin(request):
    request.session['user_name'] = request.POST['user_name']
    login_user(request.POST['user_name'], request.POST['password'])
    user_name  = request.session['user_name']
    user   = User.objects.get(user_name=user_name)
    return HttpResponseRedirect(reverse('user:profile', args=(request.POST['user_name'], )))


def mystory(request, user_name):
    context = {
        'user_name': user_name,
    }
    return render(request, 'user/mystory.html', context)


def feed(request, user_name):
    context = {
        'user_name': user_name,
    }
    return render(request, 'user/feed.html', context)


def timeline(request, user_name):
    context = {
        'user_name': user_name,
    }
    return render(request, 'user/timeline.html', context)


def projects(request, user_name):
    context = {
        'user_name': user_name,
    }
    return render(request, 'user/projects.html', context)


def following(request, user_name):
    user      = User.objects.get(user_name=user_name)
    following = user.get_following()
    context = {
        'user_name': user_name,
        'following': following,
    }
    return render(request, 'user/following.html', context)


def followers(request, user_name):
    user      = User.objects.get(user_name=user_name)
    followers = user.get_followers()
    context = {
        'user_name': user_name,
        'followers': followers,
    }
    return render(request, 'user/followers.html', context)

user/templates/user/feed.html
{% extends "user/profile.html" %}

{% block body %}


<div class="feed-content" id="feed-content">

    {% for idea in ideas %}
        <p> {{ idea.idea_title }} by {{ idea.idea_owner }} </p>
        <p> {{ idea.idea_pub }} </p>
        <p> {{ idea.idea_content }}</p>
        <p> {{ idea.idea_interested_users.count }} users are interested , {{ idea.idea_upvotes }} upvotes </p>
    {% endfor %}

</div>
<p class="lead"> This is my feed place. All my feed goes here. I know, I am lazy of writing about myself. May be other people might have fun.</p>

{% endblock %}

user/templates/user/followers.html
{% extends "user/profile.html" %}

{% block body %}

<p> Show people who follow me.</p>
{% for person in followers %}
    <span class="span8"> {{ person }} </span>
{% endfor %}

{% endblock %}

user/templates/user/following.html
{% extends "user/profile.html" %}

{% block body %}

<p> Show all the people I am following.</p>
{% for person in following %}
    <span class="span8"> {{ person }} </span>
{% endfor %}
{% endblock %}

user/templates/user/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title> User Profile </title>
    {% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet"  href="{% static 'user/css/style.css' %}" type="text/css">
    <script type="text/javascript" src="{% static 'user/jquery-3.3.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'user/js/script.js' %}"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

</head>

<div id="page">
    {% block skeleton %} {% endblock %}
    {% block body %} {% endblock %}
</div>


</html>

user/templates/user/mystory.html
{% extends "user/profile.html" %}

{% block body %}

<!--div class="navigation-bar" id="nav-bar">
        <a href="{% url 'user:feed' user_name %}">Feed</a>
        <a href="{% url 'user:timeline' user_name %}">Timeline</a>
        <a href="{% url 'user:projects' user_name %}">Projects</a>
        <a href="{% url 'user:mystory' user_name %}">My Story</a>
</div-->

{% endblock %} 

user/templates/user/profile.html
{% extends "user/layout.html" %}
{% load static %}

{% block skeleton %}
    <div class="container" id="skeleton">
        <div class="container" id="profile">
            <div class="container-fluid" id="gravatar">
                <img src="{% static 'user/images/gravatar.png' %}" class="img-rounded" width="100px" height="100px">
                <h3 class="text-left"> {{ user_name }} </h3>
            </div>

            <div class="container-fluid" id="bio">
                <h2><b> Rajiv Teja Nagipogu</b> </h2>
                <h5 class="text-left"> {{ user_about }} </h5>
                 {% if user_name == my_name %}
                    <!--button class="btn btn-primary" disabled="false">Follow &nbsp {{ no_of_followers }}</button-->
                {% else %}
                    <button class="btn btn-primary" disabled="true">Follow &nbsp {{ no_of_followers }}</button>
                {% endif %}
            </div>
        </div>


        <!--div class="container-fluid" id="sidebar-topics">
            <div class="container-fluid" id="topics">

            </div>
            <div class="toggle-on-button-press" id="tag-edit-form" hidden="true">
                    <div class="container-fluid">
                        <label for="tag">Add Tag :</label>
                        <input type="text" id="tag-input">
                        <button class="btn btn-primary" value="Add">Add</button>
                    </div>

                <button class="btn btn-primary" id="close-tag-edit">Finished Editing</button>
            </div>
            <button class="btn btn-primary active" id="tag-edit" hidden="false">Edit Tags</button>
        </div-->
        <div class="container-fluid" id="nav-bar">
            <ul class="nav navbar-nav">
                <!--li class="nav-item nav-link active"><a href="{% url 'user:feed' user_name %}">Feed</a></li-->
                 {% if user_name == my_name %}
                    <!--li class="nav-item nav-link"><a href="{% url 'user:timeline' user_name %}">Timeline</a></li-->
                 {% endif %}
                <li class="nav-item nav-link"><a href="{% url 'user:projects' user_name %}">Projects</a></li>
                <!--li class="nav-item nav-link"><a href="{% url 'user:mystory' user_name %}">My Story</a></li-->
                <li class="nav-item nav-link"><a href="{% url 'user:following' user_name %}">Following</a></li>
                <li class="nav-item nav-link"><a href="{% url 'user:followers' user_name %}">Followers</a></li>
            </ul>
        </div>
    </div>

{% endblock %}


{% block content %} {% endblock %}

user/templates/user/projects.html
{% extends "user/profile.html" %}

{% block body %}

<!--div class="navigation-bar" id="nav-bar">
        <a href="{% url 'user:feed' user_name %}">Feed</a>
        <a href="{% url 'user:timeline' user_name %}">Timeline</a>
        <a  href="{% url 'user:projects' user_name %}">Projects</a>
        <a href="{% url 'user:mystory' user_name %}">My Story</a>
</div-->

<div class="toggle-on-button-press" id="project-edit-form" hidden="true">
    <form action="/u/rajiv/projects/" method="post">
        {% csrf_token %}
        <label class="text-label"> Project Title :</label><input id="project-name" name="Project Name"><br>
        <label class="text-label"> Summary :</label><input id="project-summary" class="big-text-box"><br>
        <input type="submit" class="btn btn-primary" name="submit"><br>
    </form>
</div>
<button class="btn btn-primary active" id="project-edit" hidden="false">Edit Projects</button>

<div class="container-fluid" id="project-list">
    {% for project in user.user_projects %}
        <div class="container-fluid" id="project-box">
            <h3>{{ project.project_title }}</h3><br>
            {% for member in project.project_members %}
                <h5>{{ member.user_name }}</h5>&nbsp
            {% endfor %}<br>
            <p>{{ project.project_summary }}</p>
        </div>
    {% endfor %}
</div>

{% endblock %}

user/templates/user/timeline.html
{% extends "user/profile.html" %}

{% block body %}

<p> This is my timeline.</p>

{% endblock %}